[workspace]
resolver = "2"
members = ["macros", "node", "pipewire", "spa", "tools"]
default-members = ["macros", "node", "pipewire", "spa", "tools"]

[workspace.package]
version = "0.1.4"
license = "MIT"
repository = "https://gitlab.freedesktop.org/pipewire/pipewire-native-rs"
edition = "2021"

[workspace.dependencies]
bitflags = "2.8.0"
libc = "0.2.172"
pipewire-native-macros = { path = "macros", version = "0.1" }
pipewire-native-node = { path = "node", version = "0.1" }
pipewire-native-spa = { path = "spa", version = "0.1" }
pipewire-native = { path = "pipewire", version = "0.1" }
pipewire-native-tools = { path = "tools", version = "0.1" }
