[package]
name = "pipewire-native-wav-player"
description = "Demo: PipeWire node that plays a WAV file on repeat"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[[bin]]
name = "pw-wav-player"
path = "src/main.rs"

[dependencies]
pipewire-native.workspace = true
pipewire-native-node.workspace = true
pipewire-native-spa.workspace = true
tokio = { version = "1.44.1", features = ["macros", "net", "rt", "rt-multi-thread", "sync"] }
