[package]
name = "pipewire-native-node"
description = "Data-plane transport primitives for pipewire-native"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
libc.workspace = true
pipewire-native-spa.workspace = true
tokio = { version = "1.44.1", features = ["macros", "net", "rt", "sync"] }

[dev-dependencies]
static_assertions = "1.1.0"
