[package]
name = "pipewire-native-spa"
description = "A Rust implementation and bindings to the PipeWire SPA library"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
bitflags.workspace = true
libc.workspace = true
libloading = "0.8.6"
num = "0.4.3"
pipewire-native-macros.workspace = true

[dev-dependencies]
# For tests
libspa = "0.8.0"
static_assertions = "1.1.0"

[build-dependencies]
cc = "1.2.22"
pkg-config = "0.3.32"
